# Github action which publish a package after commits to master
name: Post-commit publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  npm-publish-and-notify:
    uses: TechSeePublic/techsee-actions/.github/workflows/npm-publish.yml@main
    with:
      branch: master
      use-slack: true
      package-name: ${{ github.repository }}
    secrets:
      git-token: ${{ secrets.GITHUB_TOKEN }}
      npm-token: ${{ secrets.NPM_PUBLISH_TOKEN }}
      slack-success-webhookurl: ${{ secrets.SLACK_NPM_PUBLISH_WEBHOOK_URL }}
      slack-failure-webhookurl: ${{ secrets.SLACK_NPM_PUBLISH_FAIL_WEBHOOK_URL }}
